const TemplateAccounts = [
    /* Aktiv Konten */
    {"code": 1000, "type": "Aktiv", "name": "Kasse", "aliases": ["Ka"], "balance": 0},
    {"code": 1020, "type": "Aktiv", "name": "Post", "aliases": ["Po"], "balance": 0},
    {"code": 1021, "type": "Aktiv", "name": "Bankguthaben", "aliases": ["Bank", "Ba"], "balance": 0},
    {"code": 1060, "type": "Aktiv", "name": "Wertschriften", "aliases": ["Ws"], "balance": 0},
    {"code": 1100, "type": "Aktiv", "name": "Forderungen aus Lieferungen und Leistungen", "aliases": ["Debitoren", "Ford. L+L", "FLL"], "balance": 0},
    {"code": 1109, "type": "Aktiv", "name": "Wertberichtigung Forderungen", "aliases": ["WB Forderungen", "WB Ford.", "Delkredere"], "balance": 0},
    {"code": 1120, "type": "Aktiv", "name": "Forderungen gegenüber Aktionäre", "aliases": [], "balance": 0},
    {"code": 1170, "type": "Aktiv", "name": "Vorsteuer MwSt Material, Waren, DL", "aliases": ["Vorsteuer 1170", "Vorst. 1170"], "balance": 0},
    {"code": 1171, "type": "Aktiv", "name": "Vorsteuer MwSt Investitionen, übriger BA", "aliases": ["Vorsteuer 1171", "Vorst. 1171"], "balance": 0},
    {"code": 1174, "type": "Aktiv", "name": "Vorsteuerkorrektur Eigenverbrauch", "aliases": [], "balance": 0},
    {"code": 1176, "type": "Aktiv", "name": "Forderung Verrechnungssteuer", "aliases": [], "balance": 0},
    {"code": 1200, "type": "Aktiv", "name": "Vorrat Handelswaren", "aliases": [], "balance": 0},
    {"code": 1210, "type": "Aktiv", "name": "Vorrat Rohstoffe", "aliases": [], "balance": 0},
    {"code": 1260, "type": "Aktiv", "name": "Vorrat Fertigfabrikate", "aliases": [], "balance": 0},
    {"code": 1270, "type": "Aktiv", "name": "Vorrat Halbfabrikate", "aliases": [], "balance": 0},
    {"code": 1300, "type": "Aktiv", "name": "Aktive Rechnungsabgrenzung", "aliases": ["Aktive RA", "ARA"], "balance": 0},
    {"code": 1440, "type": "Aktiv", "name": "Aktivdarlehen", "aliases": ["Aktiv Darl."], "balance": 0},
    {"code": 1480, "type": "Aktiv", "name": "Beteiligungen", "aliases": [], "balance": 0},
    {"code": 1500, "type": "Aktiv", "name": "Maschinen", "aliases": ["Masch"], "balance": 0},
    {"code": 1508, "type": "Aktiv", "name": "Anzahlung für Maschinen", "aliases": [], "balance": 0},
    {"code": 1509, "type": "Aktiv", "name": "Wertberichtigung Maschinen", "aliases": ["WB Masch"], "balance": 0},
    {"code": 1510, "type": "Aktiv", "name": "Mobiliar und Einrichtungen", "aliases": ["Mobiliar", "Mob"], "balance": 0},
    {"code": 1519, "type": "Aktiv", "name": "Wertberichtigung Mobiliar und Einrichtungen", "aliases": ["WB Mobiliar", "WB Mob"], "balance": 0},
    {"code": 1530, "type": "Aktiv", "name": "Fahrzeuge", "aliases": ["Fz"], "balance": 0},
    {"code": 1539, "type": "Aktiv", "name": "Wertberichtigung Fahrzeuge", "aliases": ["WB Fahrzeuge", "WB Fz"], "balance": 0},
    {"code": 1600, "type": "Aktiv", "name": "Liegenschaften", "aliases": ["Lg"], "balance": 0},
    {"code": 1609, "type": "Aktiv", "name": "Wertberichtigung Liegenschaften", "aliases": ["WB Liegenschafetn", "WB Lg"], "balance": 0},
    {"code": 1700, "type": "Aktiv", "name": "Patente, Lizenzen", "aliases": [], "balance": 0},
    {"code": 1850, "type": "Aktiv", "name": "Nicht einbezahltes Aktienkapital", "aliases": [], "balance": 0},

    /* Passiv Konten */
    {"code": 2000, "type": "Passiv", "name": "Verbindlichkeiten aus Lieferungen und Leistngen", "aliases": ["Kreditoren", "Verb. L+L", "VLL"], "balance": 0},
    {"code": 2030, "type": "Passiv", "name": "Anzahlung von Kunden", "aliases": [], "balance": 0},
    {"code": 2100, "type": "Passiv", "name": "Bankverbindlichkeiten", "aliases": [], "balance": 0},
    {"code": 2200, "type": "Passiv", "name": "Verbindlichkeit MwSt", "aliases": ["Umsatzsteuer", "Verb. MwSt"], "balance": 0},
    {"code": 2206, "type": "Passiv", "name": "Verbindlichkeit Verrechnungssteuer", "aliases": [], "balance": 0},
    {"code": 2261, "type": "Passiv", "name": "Dividenden", "aliases": [], "balance": 0},
    {"code": 2270, "type": "Passiv", "name": "Verbindlichkeiten Sozialversicherungen", "aliases": ["Verb. SozV"], "balance": 0},
    {"code": 2300, "type": "Passiv", "name": "Passive Rechnungsabgrenzung", "aliases": ["Passive RA", "PRA"], "balance": 0},
    {"code": 2330, "type": "Passiv", "name": "Kurzfristige Rückstellungen", "aliases": [], "balance": 0},
    {"code": 2401, "type": "Passiv", "name": "Hypotheken", "aliases": ["Hypo"], "balance": 0},
    {"code": 2450, "type": "Passiv", "name": "Passivdarlehen", "aliases": ["Passiv Darl."], "balance": 0},
    {"code": 2500, "type": "Passiv", "name": "Übrige langfristige Verbindlichkeiten", "aliases": [], "balance": 0},
    {"code": 2600, "type": "Passiv", "name": "Langfristige Rückstellungen", "aliases": [], "balance": 0},
    {"code": 2800, "type": "Passiv", "name": "Aktienkapital (AG)", "aliases": ["Stammkapital (GmbH)"], "balance": 0},
    {"code": 2900, "type": "Passiv", "name": "Gesetzliche Kapitalreserve", "aliases": [], "balance": 0},
    {"code": 2950, "type": "Passiv", "name": "Gesetzliche Gewinnreserve", "aliases": [], "balance": 0},
    {"code": 2960, "type": "Passiv", "name": "Freiwillige Gewinnreserve", "aliases": [], "balance": 0},
    {"code": 2970, "type": "Passiv", "name": "Gewinnvortrag", "aliases": ["Verlustvortrag"], "balance": 0},
    {"code": 2979, "type": "Passiv", "name": "Jahresgewinn", "aliases": ["Jahresverlust"], "balance": 0},
    {"code": 2850, "type": "Passiv", "name": "Privat", "aliases": [], "balance": 0},
    {"code": 2891, "type": "Passiv", "name": "Jahresgewinn", "aliases": ["Jahresverlust"], "balance": 0},

    /* Ertrag Konten */
    {"code": 3000, "type": "Ertrag", "name": "Warenertrag", "aliases": [], "balance": 0},
    {"code": 3200, "type": "Ertrag", "name": "Dienstleistungsertrag", "aliases": [], "balance": 0},
    {"code": 3400, "type": "Ertrag", "name": "Übriger Ertrag", "aliases": [], "balance": 0},

    /* Aufwand Konten */
    {"code": 4000, "type": "Aufwand", "name": "Warenaufwand", "aliases": [], "balance": 0},
    {"code": 4200, "type": "Aufwand", "name": "Personalaufwand", "aliases": [], "balance": 0},
    {"code": 4400, "type": "Aufwand", "name": "Raumaufwand", "aliases": [], "balance": 0},
    {"code": 4600, "type": "Aufwand", "name": "Abschreibungen", "aliases": [], "balance": 0},
    {"code": 4800, "type": "Aufwand", "name": "Übriger Aufwand", "aliases": [], "balance": 0},
];

module.exports = TemplateAccounts;